# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: Loadstr
    site_url: loadstr.com
    
    company_name: Kabisa ICT
    admin_email: admin@test.com
    
    support_name: Support
    support_email: support@test.com

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
